behaviors:
  SY-SW:
    trainer_type: ppo
    hyperparameters:
      batch_size: 32
      buffer_size: 256
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        strength: 0.2
        gamma: 0.99
      gail:
        gamma: 0.99
        strength: 1
        encoding_size: 64
        demo_path: Demonstrations/PlayerShipRecord.demo
        use_actions: true
    keep_checkpoints: 5
    max_steps: 15000000
    time_horizon: 64
    summary_freq: 5000
    threaded: true