default:
    trainer: ppo
    batch_size: 1024
    beta: 5.0e-3
    buffer_size: 10240
    epsilon: 0.2
    hidden_units: 128
    lambd: 0.95
    learning_rate: 3.0e-4
    max_steps: 5.0e4
    memory_size: 256
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 1000
    use_recurrent: false
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99

SY-SW:
    summary_freq: 2000
    time_horizon: 128
    batch_size: 128
    buffer_size: 2048
    hidden_units: 512
    num_layers: 2
    beta: 1.0e-2
    num_epoch: 3
    reward_signals:
        extrinsic:
            strength: 0.0
            gamma: 0.99
        gail:
            strength: 1.00
            gamma: 0.99
            encoding_size: 128
            demo_path: ./Demonstrations/PlayerShipRecord.demo
        behavioral_cloning:
            demo_path: ./Demonstrations/PlayerShipRecord.demo
            strength: 0.5